insert into greensheet values(
    'cmpe273',
    'section2',
    'spring,2017',
    'Enterprise Distributed Systems',
    'Sithu Aung',
    'ENG 2',
    'Sithu.xxxx@sjsu.edu',
    'Wednesday 5:00pm-6:00pm by Appointment Only',
    'Wednesday 6:00pm–8:45pm',
    'DMH 227',
    'Strong in a OOP or functional programming language',
    'https://sjsu.instructure.com',
    'The objective of this course is to introduce you to the architecture principles, application protocols, Web Service API design and integration patterns for building distributed system.',
    'Introduction to application protocols for large scale distributed systems including object request brokers, asynchronous messaging, and Web services. Lab is based on using protocols to build distributed systems',
    'There is no text that really corresponds to the material and focus of this course.',
    'This course consists of a single lecture per week.  In-class activities including hands-on labs will be given to encourage attendance. You are encouraged to consult with me on your group project to make sure it is successful. Students are responsible for understanding the policies and procedures about add/drops, academic renewal, etc. Information on add/drops is available at http://info.sjsu.edu/web-dbgen/narr/soc-fall/rec-298.html. Information about late drop is available at http://www.sjsu.edu/sac/advising/latedrops/policy/. Students should be aware of the current deadlines and penalties for adding and dropping classes.',
    'There will be no make-up exam. Absence from the scheduled final exam will result in a failing grade in the  course unless documented reasons are submitted to the instructor and receiving a written approval from the instructor before the exam.',
    'All  the  assignments  and  project  code  must  be  submitted  electronically  to  your GitHub/Bitbucket’s repository.  All assignments and the final exam must be done individually.'
);
